FROM node:20.12.2-alpine AS build

RUN apk update --no-cache \
    && apk add git bash openssh-client yarn bind-tools graphicsmagick
    # && apk add git bash python3 make gcc g++ openssh-client yarn bind-tools graphicsmagick

WORKDIR /dx-api
COPY . /dx-api
ARG NODE_ENV
ARG GITHUB_TOKEN

ENV NODE_ENV=$NODE_ENV
ENV GITHUB_TOKEN=$GITHUB_TOKEN

RUN npm install -g npm@10.8.1 nx gm
RUN yarn global add nx@latest nodemon --no-optional
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc
RUN --mount=type=secret,id=gitconfig,target=/root/.gitconfig

RUN yarn ci && rm -rf ~/.npmrc
RUN yarn build

COPY _devops /opt/devops

CMD ["yarn", "serve"]
