FROM node:20.12.2-alpine AS build

RUN apk update --no-cache \
    && apk add git bash python3 make gcc g++ openssh-client yarn bind-tools

WORKDIR /dx-api
COPY . /dx-api
ARG NODE_ENV
ARG GITHUB_TOKEN

ENV NODE_ENV=$NODE_ENV
ENV GITHUB_TOKEN=$GITHUB_TOKEN

RUN echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc && npm config set @umg:registry https://npm.pkg.github.com

RUN yarn ci && rm -rf ~/.npmrc
RUN yarn build

COPY _devops /opt/devops

CMD ["yarn", "serve"]
