services:
  redis:
      image: redis:7-alpine
      ports:
          - "6379:6379"
      container_name: "redis"
  postgres:
      image: postgres:16-alpine
      volumes:
        - "db-data:/var/lib/postgresql/data/pgdata"
      environment:
          PGDATA: "/var/lib/postgresql/data/pgdata"
          POSTGRES_USER: "pguser"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "dx-nx"
      ports:
          - "5433:5432"
      container_name: "postgres"
  sendgrid:
    image: ghashange/sendgrid-mock:1.7.2
    container_name: 'sendgrid'
    ports:
      - '7070:3000'
    environment:
      - API_KEY=${SENDGRID_API_KEY}
  monorepo-node-20:
    extends:
        file: ./docker-compose.base.yml
        service: base
    container_name: 'monorepo'
    tty: true
    stdin_open: true
    build:
        context: .
        dockerfile: ./_devops/docker/Dockerfile.local
    command: "/bin/bash"
    volumes:
        - $PWD/:/app
    ports:
        - "4000:4000"
    depends_on:
        - redis
        - postgres
        - sendgrid
    links:
        - redis
        - postgres
        - sendgrid
    environment:
        - ROOT_DIR=/app
secrets:
  npmrc:
    file: $HOME/.npmrc
  gitconfig:
    file: $HOME/.gitconfig
volumes:
  db-data:
