services:
  redis:
      image: redis:7-alpine
      ports:
          - "6379:6379"
      container_name: "redis"
  postgres:
      image: postgres:16-alpine
      volumes:
        - "db-data:/var/lib/postgresql/data/pgdata"
      environment:
          PGDATA: "/var/lib/postgresql/data/pgdata"
          POSTGRES_USER: "pguser"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "dx-nx"
      ports:
          - "5433:5432"
      container_name: "postgres"
  sendgrid:
    image: ghashange/sendgrid-mock:1.7.2
    container_name: 'sendgrid'
    ports:
      - '7070:3000'
    environment:
      - API_KEY=${SENDGRID_API_KEY}
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  monorepo-node-22:
    extends:
        file: ./docker-compose.base.yml
        service: base
    container_name: 'monorepo'
    tty: true
    stdin_open: true
    build:
        context: .
        dockerfile: ./_devops/docker/Dockerfile.local
    command: "/bin/bash"
    volumes:
        - $PWD/:/app
    ports:
        - "4000:4000"
        - "4200:4200"
        - "4211:4211"
        - "8081:8081"
        - "19000:19000"
        - "19001:19001"
        - "19002:19002"
        - "36439:36439"
    depends_on:
        - redis
        - postgres
        - localstack
        - sendgrid
    links:
        - redis
        - postgres
        - sendgrid
    environment:
        - ROOT_DIR=/app
secrets:
  npmrc:
    file: $HOME/.npmrc
  gitconfig:
    file: $HOME/.gitconfig
volumes:
  db-data:
