import {
  TableMeta
} from '@dx/ui-web';

// In the order they should appear left to right
export const userAdminTableMetaData: TableMeta[] = [
  {
    align: 'left',
    componentType: 'text',
    fieldName: 'fullName',
    fieldType: 'string',
    headerAlign: 'left',
    title: 'Name',
    sortable: true,
    width: '15%',
  },
  {
    align: 'left',
    componentType: 'text',
    fieldName: 'username',
    fieldType: 'string',
    headerAlign: 'left',
    title: 'Username',
    sortable: true,
    width: '15%',
  },
  {
    align: 'left',
    componentType: 'text',
    fieldName: 'emails',
    fieldType: 'string',
    headerAlign: 'left',
    title: 'Email',
    sortable: false,
    width: '25%',
  },
  {
    align: 'left',
    componentType: 'text',
    fieldName: 'phones',
    fieldType: 'string',
    headerAlign: 'left',
    title: 'Phone',
    sortable: false,
    width: '15%',
  },
  {
    align: 'center',
    componentType: 'icon',
    fieldName: 'isAdmin',
    fieldType: 'boolean',
    headerAlign: 'center',
    title: 'Admin',
    sortable: true,
    width: '5%',
  },
  {
    align: 'center',
    componentType: 'icon',
    fieldName: 'isSuperAdmin',
    fieldType: 'boolean',
    headerAlign: 'center',
    title: 'Super',
    sortable: true,
    width: '5%',
  },
  {
    align: 'center',
    componentType: 'icon',
    fieldName: 'optInBeta',
    fieldType: 'boolean',
    headerAlign: 'center',
    title: 'Beta',
    sortable: true,
    width: '5%',
  },
  {
    align: 'center',
    componentType: 'icon',
    fieldName: 'restrictions',
    fieldType: 'boolean',
    headerAlign: 'center',
    title: 'Restricted',
    sortable: true,
    width: '10%',
  },
  {
    align: 'left',
    componentType: 'none',
    fieldName: '',
    fieldType: null,
    headerAlign: 'center',
    title: '',
    sortable: false,
    width: '5%',
  }
];
