export {
  API_HOST_PORT,
  API_URL,
  APP_DESCRIPTION,
  APP_DOMAIN,
  APP_NAME,
  APP_PREFIX,
  COMPANY_NAME,
  DEFAULT_LIMIT,
  DEFAULT_OFFSET,
  DEFAULT_SORT,
  LOCAL_ENV_NAME,
  PHONE_DEFAULT_REGION_CODE,
  PROD_ENV_NAME,
  SORT_DIR,
  STAGING_ENV_NAME,
  WEB_DOMAIN,
  WEB_URL
} from './lib/common-config.consts';
export { DISPOSABLE_EMAIL_DOMAINS } from './lib/disposable-email-providers';
export { INVALID_EMAIL_NAMES } from './lib/email-validation.const';

// Test Data
// export {
//   TEST_COUNTRY_CODE,
//   TEST_DEVICE,
//   TEST_EMAIL,
//   TEST_EXISTING_EMAIL,
//   TEST_EXISTING_PASSWORD,
//   TEST_EXISTING_PHONE,
//   TEST_EXISTING_USER_ID,
//   TEST_EXISTING_USER_PRIVILEGE_ID,
//   TEST_FIRST_NAME,
//   TEST_LAST_NAME,
//   TEST_PASSWORD,
//   TEST_PHONE,
//   TEST_PHONE_IT_INVALID,
//   TEST_PHONE_IT_VALID,
//   TEST_PHONE_VALID,
//   TEST_USERNAME,
//   TEST_USER_CREATE,
//   TEST_UUID,
// } from './lib/tests/test.const';
