export const UNSUBSCRIBE_GROUPS = {
  MARKETING: 16961,
  TRANSACTIONAL: 16959,
  INVITES: 16958,
  AFFILIATE_NOTIFICATIONS: 16960
};

export const IP_POOL_NAME = {
  INVITES: 'invites',
  TRANSACTIONAL: 'transactional'
};
