export const CUSTOM_PROFANE_WORDS = [
  'custom-test',
  '4chan',
  'baccarat',
  'blackjack',
  'casino',
  'craps',
  'gamble',
  'gambling',
  'online gambling',
  'poker',
  'roulette',
  'slot machine',
  "texas hold'em",
  'a2m ',
  'acrotomophilia',
  'adult ',
  'amateur',
  'anal',
  'anilingus',
  'annie sprinkle',
  'anus',
  'apple bong howto',
  'are idiots',
  'arsehole',
  'aryan',
  'asexual',
  'asian babe',
  'ass',
  'asshole',
  'assmunch',
  'auto erotic',
  'autoerotic',
  'babes in toyland',
  'babeland',
  'baby batter',
  'baby chowder',
  'ball gravy',
  'ball sack',
  'ball gag',
  'ball kicking',
  'ball licking',
  'ball sucking',
  'bangbros',
  'bareback',
  'barely legal',
  'barenaked ladies',
  'bastard',
  'bastardo',
  'bastinado',
  'bbw',
  'bdsm ',
  'beaner',
  'bearded clam',
  'beaver cleaver',
  'beaver lips',
  'behind the green door',
  'bestiality',
  'betty dodson',
  'bi curious',
  'bianca beauchamp',
  'big black',
  'big knockers ',
  'big tits',
  'bimbo',
  'bimbos',
  'birdlock',
  'bisexual',
  'bitch',
  'black cock',
  'blonde action ',
  'blonde on blonde action ',
  'blood play',
  'blow',
  'blow j',
  'blow your l',
  'bludgeon',
  'blue waffle',
  'blumpkin',
  'bollocks',
  'bondage ',
  'boner',
  'boob',
  'booty call',
  'breast',
  'brown showers',
  'brunette action',
  'bugger',
  'bukkake',
  'bulldyke',
  'bullet vibe',
  'bumming',
  'bung hole',
  'bunghole',
  'busty',
  'butt',
  'butthole',
  'buttcheeks',
  'buttcrack',
  'buttocks',
  'camel toe',
  'camgirl',
  'camslut',
  'camwhore',
  'carnage',
  'carol queen',
  'carpet muncher',
  'carpetmuncher',
  'chastity belt',
  'chink',
  'chocolate rosebuds',
  'chrissie wunna',
  'church of satan',
  'circlejerk',
  'cleveland steamer',
  'clit',
  'clitoral',
  'clitoris',
  'clitoritis',
  'clover clamps',
  'clusterfuck',
  'cocaine',
  'cock',
  'cocks',
  'cocksucker',
  'commie',
  'consensual intercourse',
  'coprolagnia',
  'coprophilia ',
  'coprophagia',
  'cornhole',
  'cory silverberg',
  'courtney trouble',
  'crack',
  'cream pie',
  'creampie',
  'crossdresser',
  'cuckold',
  'cum',
  'cumming',
  'cunt',
  'cunnilingus',
  'dago',
  'darkie',
  'date rape',
  'daterape',
  'deep throat',
  'deepthroat',
  'dick',
  'diddy ride',
  'dildo',
  'dirty pillows',
  'dirty sanchez',
  'disembowel',
  'dismember',
  'dog style',
  'doggie style',
  'doggiestyle',
  'doggy style',
  'doggystyle',
  'dolcett',
  'domination',
  'dominatrix',
  'dommes',
  'donkey punch',
  'dothead',
  'double dong',
  'double penetration',
  'dp action',
  'ducky doolittle',
  'dutch oven',
  'dyke',
  'eat my ass',
  'ecchi',
  'ecstasy',
  'ejaculation',
  'electrotorture',
  'erection',
  'erotic',
  'erotism',
  'escort',
  'ethical slut',
  'eunuch',
  'excrement',
  'extreme elvis',
  'fag',
  'faggot',
  'faggot',
  'fantasies',
  'fapserver',
  'fascist',
  'fecal',
  'felatio',
  'felch',
  'fellatio',
  'feltch',
  'femdom',
  'feminazi',
  'fetish',
  'figging',
  'filthy sanchez',
  'fingering ',
  'fisting',
  'flick the bean',
  'foot fetish',
  'footjob',
  'foreplay',
  'fornicate',
  'foursome',
  'freeones',
  'frotting',
  'fuck',
  'fuck buttons',
  'fudge packer',
  'fudgepacker',
  'fuh q',
  'fuhq',
  'fuhk',
  'fuhkt',
  'futanari',
  'g-spot',
  'g-string',
  'gang bang',
  'gay boy',
  'gay dog',
  'gay man',
  'gay men',
  'gay sex',
  'genitals',
  'get my sister',
  'giant cock',
  'ginger lynne',
  'girl on',
  'girl on top',
  'girls gone wild',
  'goat.se',
  'goatcx',
  'goatse',
  'gokkun',
  'golden shower',
  'golliwog',
  'goo girl',
  'good poop',
  'goodpoop',
  'goodvibes',
  'google is evil',
  'gook',
  'goregasm',
  'got my sister',
  'greaser',
  'gringo',
  'grope',
  'group sex',
  'gtfo',
  'guro',
  'hairy',
  'hand job',
  'handjob',
  'happy slapping video',
  'hard core',
  'hardcore',
  'hate',
  'hebe',
  'hedop',
  'hentai',
  'hermaphrodite',
  'heroin',
  'heroin',
  'heterosexual',
  'hickey',
  'holdem',
  'homoerotic',
  'homosexual',
  'honkey',
  'honky',
  'hookup',
  'hooker',
  'hot chick',
  'hottie',
  'huge fat',
  'humping',
  'hustler',
  'i hate',
  'impalement',
  'incest',
  'injun',
  'insertions',
  'interracial',
  'jack off',
  'jackie strano',
  'jacobs ladder piercing',
  'jail bait',
  'jailbait',
  'jenna jameson',
  'jerk off ',
  'jesse jane',
  'jizz',
  'jigaboo',
  'jiggaboo',
  'jiggerboo',
  'john holmes',
  'jordan capri',
  'juggs',
  'kama',
  'kamasutra',
  'kike',
  'kinbaku',
  'kinky',
  'kinkster',
  'kinsey institute',
  'kkk',
  'knobbing ',
  'ku klux klan',
  'labia',
  'latina',
  'leather restraint',
  'lemon party',
  'lemonparty',
  'lesbian',
  'licked',
  'lingerie',
  'lolita',
  'lovemaking',
  'lovers',
  'lsd',
  'madison young',
  'make me come',
  'making love',
  'male squirting',
  'marijuana',
  'marijuana',
  'masturbate ',
  'mature',
  'mdma',
  'meats',
  'menage a trois',
  'merkin',
  'miki sawaguchi',
  'milf',
  'missionary',
  'missionary position',
  'money shot',
  'motherfucker',
  'mound of venus',
  'muff diver',
  'muffdiving',
  'murder',
  'murder',
  'naked',
  'nambla',
  'naughty',
  'nawashi',
  'nazi',
  'necrophilia',
  'negro',
  'neonazi',
  'nig nog',
  'nigga',
  'nigger',
  'nimphomania',
  'nina hartley',
  'nipple',
  'nipples',
  'nonconsent',
  'nsfw images',
  'nude',
  'nut butter',
  'nympho',
  'nymphomania',
  'octopussy',
  'octopussoir',
  'omorashi',
  'oral',
  'oral sex',
  'orgy',
  'orgasm',
  'outercourse',
  'paedophile',
  'pansy',
  'panty',
  'panties',
  'pecker',
  'pedobear',
  'pedophile',
  'peep show',
  'pegging',
  'penetration',
  'penis',
  'penthouse',
  'pervert',
  'philip kindred dick',
  'phone sex',
  'phuk',
  'phuker',
  'puhkt',
  'pickaninny',
  'piece of shit',
  'pinko',
  'piss',
  'piss pig',
  'pissing',
  'pisspig',
  'playboy',
  'pleasure chest',
  'pole smoker',
  'ponyplay',
  'poof',
  'poofter',
  'poop chute',
  'poopchute',
  'porn',
  'pr0n',
  'pre teen',
  'preteen',
  'prolapsed',
  'prostitute',
  'pthc',
  'pubes',
  'pubic',
  'puppy play',
  'pussy',
  'pssy',
  'pussyluvr',
  'pssylvr',
  'queaf',
  'queef',
  'quickie',
  'quim',
  'r@ygold',
  'raghead',
  'raging boner',
  'rape',
  'raping',
  'rapist',
  'rapping women',
  'rectum',
  'redtube',
  'redskin',
  'renob',
  'retard',
  'reverse cowgirl',
  'rimjob',
  'rimming',
  'roman shower',
  'rosy palm',
  'rule 34',
  'russian brides',
  'rusty trombone',
  's and m',
  's&m',
  'sadism',
  'sadist',
  'sambo',
  'sausage party',
  'scat',
  'schlong',
  'schoolgirl',
  'schoolboy',
  'scissoring',
  'seduced',
  'seductive',
  'semen',
  'servitude',
  'serviture',
  'sex',
  'sexo',
  'sexy',
  'shemale',
  'shibari',
  'shit',
  'shocker',
  'shota',
  'shrimping',
  'sissy',
  'size queen',
  'sjambok',
  'skank',
  'slanteye',
  'sleazy d',
  'slit',
  'slut',
  'smut',
  'snatch',
  'snowballing',
  'sodomize',
  'sodomy',
  'spank',
  'speculum',
  'sperm',
  'spic',
  'spooge',
  'spook',
  'spread legs',
  'spunky teens',
  'squirt',
  'stab',
  'stickam girl',
  'stileproject',
  'stormfront',
  'strap on',
  'strapon',
  'strappado',
  'submissive',
  'submission',
  'suck',
  'sucks',
  'swastika',
  'swinger',
  'teen',
  'tentacle',
  'testicle',
  'thong',
  'threesome',
  'throating',
  'tit',
  'titties ',
  'titty',
  'tosser',
  'towelhead',
  'traci lords',
  'tranny',
  'transexual',
  'transgender',
  'tribadism',
  'trisexual',
  'tub girl',
  'tubgirl',
  'turd',
  'tushy',
  'twat',
  'twink',
  'twinkie',
  'upskirt',
  'urethra',
  'urophilia',
  'vagina',
  'vagisil',
  'vanilla rosebuds',
  'venus mound',
  'vibrator',
  'vivid',
  'vorarephilia',
  'voyeur',
  'vulva',
  'wank',
  'webcam',
  'wet dream',
  'wetback',
  'white power',
  'whore',
  'wigger',
  'wtf',
  'yaoi',
  'yellow showers',
  'yiffy',
  'zoophilia',
];
